# Generated by Django 4.2.7 on 2023-11-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interactor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
