# Generated by Django 4.2.7 on 2023-11-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_interactor_address_and_more'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agent_sales', to='master.interactor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='interactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactor_sales', to='master.interactor'),
        ),
    ]
