# Generated by Django 4.2.7 on 2023-11-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('sale', '0002_sale_agent_alter_sale_interactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='agent.agent'),
        ),
    ]
